### ISSUE TITLE
Add screenshots to readme

### ISSUE THREAD

**Issue by GroovinChip** [tusharsadhwani/flutter_sidebar#1]
I suggest you add screenshots to your readme so people can see what your widget looks like.

**Comment by onesquarepeg** [comment]
oh lol right add the screenshots

**Comment by tusharsadhwani** [comment]
Yeah, I'm planning to do that as soon as I finalize the widget API.

Thanks for the suggestion though! Did you try using the package?

**Comment by GroovinChip** [comment]
I did not. I browse pub a lot, and I don't try packages without screenshots or detailed readmes. Just wanted to help you guys out.

**Comment by tusharsadhwani** [comment]
Thanks man, will do :)
